version: "3.7"
services:
  backend:
    build:
      context: ./api
    hostname: api
    restart: always
    container_name: api
    ports:
      - 7860:7860
    env_file:
      - .env
    volumes:
      - ./api:/api
    depends_on:
      neo4j:
        condition: service_healthy
  frontend:
    build:
      context: ./ui
    hostname: ui
    restart: always
    container_name: ui
    ports:
      - 4173:4173
    env_file:
      - .env
    depends_on:
      neo4j:
        condition: service_healthy
  neo4j:
    image: "neo4j:5.9.0"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
    ports:
      - 7687:7687
      - 7474:7474
    healthcheck:
      test: ["CMD", "wget", "http://localhost:7474"]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 40s
